2023 restructurisation
nfarukshin/studchr-faq pull request #17
Opened 2022-12-08 15:07 UTC by nfarukshin

Поправил основную часть файлов, кроме организаторской части

2022-12-10 18:47 UTC, dzhiiana requested changes

2022-12-10 18:47 UTC, dzhiiana commented on for-elders.md
>  Можно, [Положение](https://drive.google.com/file/d/1tGAe31MBBnZAgFj0f4y2js_J_n0DKunC/view) этого не запрещает. Однако в этом случае в [отборочном или заявочном составе](https://vk.com/@chgk_student-f
в этом случае наверн надо убрать, в любом случае иностранцев дб не более двух

2022-12-10 18:47 UTC, dzhiiana commented on for-elders.md
> +## Как перейти из команды в команду в течение сезона?
вернуть заголовок про иностранца?

2022-12-10 18:47 UTC, dzhiiana commented on for-elders.md
> +Количество **баллов за перформанс** зависит от того, насколько сильных противников обыграла ваша команда. Чтобы это выяснить, для каждой команды, участвующей в выводящем турнире, определяется ее сила
мб чтобы не менять каждый сезон + не звучало как будто в этом году на основе последнего чемпионата а в другой раз может быть на чём-то другом написать 

```
определяется коэффициент силы. Он высчитывается исходя из результатов каждого из игроков команды на последнем СтудЧРе. Из коэффициентов обыгранных вами команд выбираются пять наибольших — их сумма и составляет бонусную часть отборочных баллов.
```

2022-12-11 11:16 UTC, nfarukshin commented on for-elders.md
>  Можно, [Положение](https://drive.google.com/file/d/1tGAe31MBBnZAgFj0f4y2js_J_n0DKunC/view) этого не запрещает. Однако в этом случае в [отборочном или заявочном составе](https://vk.com/@chgk_student-f
Чуть-чуть заменю тогда формулировку тут.

2022-12-11 11:16 UTC, nfarukshin commented on for-elders.md
> +## Как перейти из команды в команду в течение сезона?
да, чот я тут затупил

2022-12-11 11:27 UTC, nfarukshin commented on for-elders.md
> +Количество **баллов за перформанс** зависит от того, насколько сильных противников обыграла ваша команда. Чтобы это выяснить, для каждой команды, участвующей в выводящем турнире, определяется ее сила
Я не уверен, что это коэффициентом можно назвать, это скорее... показатель, что ли? Подумаю ещё, как сказать. (да, я помню, что там указан коэффициент, заменю числом).

2022-12-11 19:43 UTC, dzhiiana approved these changes

2022-12-11 19:50 UTC, merged